[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "easelenium"
version = "0.7.2"
requires-python = ">=3.8"
readme = { file = "README.md", content-type = "text/markdown" }
description = "easelenium - Selenium-based Test Automation Framework."
authors = [
    { name = "Kirill Strelkov", email = "kirillstrelkov@users.noreply.github.com" },
]
dependencies = [
    "selenium",
    "attrdict3",
    "pytest",
    "pytest-html",
    "loguru",
    "webdriver-manager",
]

[project.optional-dependencies]
gui = ["wxPython"]

[project.scripts]
easelenium_cli = "easelenium.scripts.easelenium_cli:main"
easelenium_ui = "easelenium.scripts.easelenium_ui:main"

[dependency-groups]
dev = [
    "pyright>=1.1.409",
    "pytest-cov",
    "pytest-dotenv",
    "pytest-profiling",
    "ruff",
]

[tool.hatch.build.targets.wheel]
packages = ["easelenium"]
