line-length = 120
indent-width = 4

[lint]
select = ["ALL"]
ignore = ["INP001", "D203", "D213", "COM812"]
unfixable = ["B"]

[lint.per-file-ignores]
"tests/**/*_test.py" = [
    "S101",
    "FBT001",
    "D103",
    "SLF001",
    "E501",
    "TD002",
    "TD003",
    "ANN",
]
"tests/**/__init__.py" = ["D104", "D103", "SLF001", "ANN"]
"tests/data/*" = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
