name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt purge chromium* 
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt -f install
          sudo apt install -y xvfb firefox
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
          uv tool install rust-just
      - name: Run tests
        run: |
          just test-ci
